### ISSUE TITLE
Make CEMRG remember the previous perspective

### ISSUE THREAD

**Issue by drsewilliams** [CemrgAppDevelopers/CemrgApp#26] opened 2020-09-09 13:16 UTC
Iain has watched me do this just now - I have made the default perspective scar quantification; reloaded; but it has defaulted to the motion tracking perspective having been open for about 10 minutes.

**Comment by alonsoJASL** [comment] 2020-09-11 08:37
This does not seem right, as MITK (and CemrgApp, by extension) should keep track of the previous perspective. At this point it's very difficult to troubleshoot this, as there's not much information. I have had this problem as well, but I could not tell how to reproduce it. It seems to be random, in my experience.

Do you remember if there is anything else about this? Has your CemrgApp crashed before reloading?  

If this issue does not seem to be fully random for you, maybe you can help us by going through our [Reporting bugs](https://github.com/CemrgAppDevelopers/CemrgApp/wiki/Reporting-bugs) site, which has some guidelines on how to get more information for us; or more simply, check our [issue template](https://github.com/CemrgAppDevelopers/CemrgApp/wiki/ISSUE_TEMPLATE.md), which has a checklist.

**Comment by drsewilliams** [comment] 2020-09-12 13:57
Hi Jose

I agree. Seems a bit random. I’ve not been able to work out a reproducible way to reproduce it. I’ll keep an eye.

In the meantime: does the randomness help: eg considering where the state is saved; how persistence (is meant to be achieved); how the OS interacts with these files?

Steven

Dr Steven Williams BSc MBChB PgCert PhD MRCP(UK) MIET FHEA
Clinical Lecturer and Honorary Specialty Registrar in Cardiac Electrophysiology
Division of Imaging Sciences & Biomedical Engineering
King’s College London
Joint Clinical Lead (Atrial Fibrillation Theme), London Medical Imaging and AI Centre for Value Based Healthcare
steven.e.williams@kcl.ac.uk
Tel: 020 7188 7188 ext 56308

**Comment by OrodRazeghi** [comment] 2020-10-27 13:31
Hi, the previously open perspective is saved by MITK as cached state somewhere in user's home directory. To confirm, if you run CemrgApp from a terminal with the BlueBerry.clean flag:

`./CemrgApp --BlueBerry.clean`

All cached data will be removed and the default perspective (Motion Estimation) will be presented in the new launch. If the previously used perspective only disappeared randomly for you and not consistently, it might be that the cache was removed by the OS. For now I will close this issue, but feel free to reopen it, if the problem continues to persist.

**Closed by OrodRazeghi** 2020-10-27 13:31 UTC
Labels: bug, invalid
