### ISSUE TITLE
[WathCa] The app quits unexpectedly after clipping PVs

### ISSUE THREAD

**Issue by alonsoJASL** [CemrgAppDevelopers/CemrgApp#18] opened 2020-07-14 10:44 UTC
This issue was originally reported in #17 and reported by @dariadg 

After doing a couple of cases, the App would quit: 

- It would always quit after I’ve loaded a new image, then pressed: “Segment Images”.
- It would ask: “Do you have a segmentation to load”. I’d answer: “No”.
- [Then] it shuts down completely.

**Comment by OrodRazeghi** [comment] 2020-08-17 20:59
As the tested, the issue is most likely due to failure of generating centrelines or clipper planes. A number of safeguards are now added to alert the user, if the process fails. It may still be necessary to reevaluate the meshing tool used at the moment for clipping the veins.

**Comment by OrodRazeghi** [comment] 2020-09-30 22:26
So, it seems that the crash can occur when the user clicks on clipper planes button in the PV clipper view. Debugging the code shows that segmentation fault is caused by the vtkvmtkPolyDataCenterlineSections filter:

_vtkSmartPointer<vtkvmtkPolyDataCenterlineSections> ctrLineSects;
ctrLineSects->SetInputData(surface->GetVtkPolyData());
ctrLineSects->SetCenterlines(line);
ctrLineSects->SetCenterlineSectionAreaArrayName("CentrelineSectionAreaArrayName");
ctrLineSects->SetCenterlineSectionMinSizeArrayName("CenterlineSectionMinSizeArrayName");
ctrLineSects->SetCenterlineSectionMaxSizeArrayName("CenterlineSectionMaxSizeArrayName");
ctrLineSects->SetCenterlineSectionShapeArrayName("CenterlineSectionShapeArrayName");
ctrLineSects->SetCenterlineSectionClosedArrayName("CenterlineSectionClosedArrayName");
ctrLineSects->Update(); //update causes the crash_

And the filter fails most likely due to degenerate triangles of the decimated mesh. We need to find a way to clean the mesh after decimation or remove the decimation code all together and find a better meshing tool with control over meshing resolution.

**Comment by OrodRazeghi** [comment] 2020-10-06 17:58
I added polydata cleaning and recalculating normals filters to the code after the decimation step. It seems it has stopped the crashes in cases sent to us that had issues in the past. @alonsoJASL can you please run some tests on the new clipping code? If it works, I think we can close this issue.

**Comment by OrodRazeghi** [comment] 2020-10-27 13:41
By using **vtkPolyDataConnectivityFilter** and **vtkWindowedSincPolyDataFilter** after the decimation step, the problem seems to be fixed.

**Closed by OrodRazeghi** 2020-10-27 13:41 UTC
Labels: bug
