### ISSUE TITLE
Have to authorise use of various command line programs on the first launch of the programme

### ISSUE THREAD

**Issue by drsewilliams** [CemrgAppDevelopers/CemrgApp#22] opened 2020-07-30 13:29 UTC
This could just be documented for the time being in the wiki on how to install.

**Comment by alonsoJASL** [comment] 2020-08-07 11:46
This is a duplicate of #21 

I will add an entry to the wiki pointing to this issue,

**Closed by alonsoJASL** 2020-08-07 11:46 UTC
Labels: documentation, duplicate
